PDFS = TJRC_report_Volume_1.pdf TJRC_report_Volume_2A.pdf TJRC_report_Volume_2B.pdf TJRC_report_Volume_2C.pdf TJRC_report_Volume_3.pdf TJRC_report_Volume_4.pdf 

all: $(PDFS)

$(PDFS):
	curl -O http://www.tjrckenya.org/images/documents/$@
